# Generated by Django 3.2.23 on 2023-12-11 13:41

from django.db import migrations, models
import django.db.models.deletion
import django_slack_bot.models.message_recipient


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Slack channel where messages will be sent.', max_length=32, verbose_name='Channel')),
                ('mentions', django_slack_bot.models.message_recipient.SeparatedValuesField(help_text='List of mentions, user or groups in Slack ID (e.g. U06A2DMBTTJ).', verbose_name='Mentions')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
            },
        ),
        migrations.CreateModel(
            name='SlackMessagingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique message code for lookup, mostly by human.', max_length=32, unique=True, verbose_name='Code')),
                ('enabled', models.BooleanField(default=True, help_text='Turn on or off current messaging policy.', verbose_name='Enabled')),
                ('recipients', models.ManyToManyField(help_text='Those who will receive messages.', to='django_slack_bot.SlackMessageRecipient', verbose_name='Message recipients')),
            ],
            options={
                'verbose_name': 'Messaging Policy',
                'verbose_name_plural': 'Messaging Policies',
            },
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField(help_text='Message body.', verbose_name='Body')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether this message sent.', verbose_name='Sent')),
                ('ts', models.CharField(default='', help_text='ID of an Slack message.', max_length=32, unique=True, verbose_name='Message ID')),
                ('parent_ts', models.CharField(default='', help_text='ID of current conversation thread.', max_length=32, verbose_name='Thread ID')),
                ('request', models.JSONField(help_text='Dump of request content for debugging.', verbose_name='Request')),
                ('response', models.JSONField(help_text='Dump of response content for debugging.', verbose_name='Response')),
                ('policy', models.ForeignKey(help_text='Messaging policy for this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_slack_bot.slackmessagingpolicy', verbose_name='Messaging Policy')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
