# Generated by Django 3.2.23 on 2023-12-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackmessage',
            name='request',
            field=models.JSONField(help_text='Dump of request content for debugging.', null=True, verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='response',
            field=models.JSONField(help_text='Dump of response content for debugging.', null=True, verbose_name='Response'),
        ),
    ]
