# Generated by Django 3.2.23 on 2023-12-25 02:07
from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps


def _forwards_func(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    db_alias: str = schema_editor.connection.alias
    SlackMention = apps.get_model("django_slack_bot", "SlackMention")

    SlackMention.objects.using(db_alias).get_or_create(type="R", name="Here", mention="<!here>")
    SlackMention.objects.using(db_alias).get_or_create(type="R", name="All", mention="<!all>")
    SlackMention.objects.using(db_alias).get_or_create(type="R", name="Everyone", mention="<!everyone>")


def _reverse_func(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    db_alias: str = schema_editor.connection.alias
    SlackMention = apps.get_model("django_slack_bot", "SlackMention")

    SlackMention.objects.using(db_alias).filter(type="R", name="Here", mention="<!here>").delete()
    SlackMention.objects.using(db_alias).filter(type="R", name="All", mention="<!all>").delete()
    SlackMention.objects.using(db_alias).filter(type="R", name="Everyone", mention="<!everyone>").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("django_slack_bot", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code=_forwards_func, reverse_code=_reverse_func),
    ]
