# Generated by Django 3.2.23 on 2023-12-17 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When instance created.', verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='When instance modified recently.', verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='slackmessagerecipient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When instance created.', verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackmessagerecipient',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='When instance modified recently.', verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='slackmessagingpolicy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When instance created.', verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackmessagingpolicy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='When instance modified recently.', verbose_name='Last Modified'),
        ),
    ]
