# Generated by Django 3.2.23 on 2023-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_slack_bot", "0002_create_special_mentions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackmention",
            name="type",
            field=models.CharField(
                choices=[("U", "User"), ("G", "Group"), ("S", "Special"), ("?", "Unknown")],
                help_text="Type of mentions.",
                max_length=1,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="slackmessagerecipient",
            name="channel",
            field=models.CharField(
                help_text="Slack channel ID where messages will be sent.",
                max_length=128,
                verbose_name="Channel",
            ),
        ),
    ]
