# Generated by Django 3.2.23 on 2023-12-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0002_auto_20231211_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackmessage',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='ok',
            field=models.BooleanField(default=None, help_text='Whether Slack API respond with OK. If never sent, will be `null`.', null=True, verbose_name='OK'),
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='ts',
            field=models.CharField(default='', help_text='ID of an Slack message.', max_length=32, verbose_name='Message ID'),
        ),
    ]
