# Generated by Django 3.2.23 on 2023-12-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0002_auto_20231217_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackmessage',
            options={'ordering': ('-created',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='parent_ts',
            field=models.CharField(blank=True, default='', help_text='ID of current conversation thread.', max_length=32, verbose_name='Thread ID'),
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='Messaging policy for this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_slack_bot.slackmessagingpolicy', verbose_name='Messaging Policy'),
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='request',
            field=models.JSONField(blank=True, help_text='Dump of request content for debugging.', null=True, verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='response',
            field=models.JSONField(blank=True, help_text='Dump of response content for debugging.', null=True, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='slackmessage',
            name='ts',
            field=models.CharField(blank=True, help_text='ID of an Slack message.', max_length=32, null=True, unique=True, verbose_name='Message ID'),
        ),
    ]
