# Generated by Django 3.2.23 on 2023-12-11 14:41

from django.db import migrations, models
import django_slack_bot.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0003_auto_20231211_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmessagingpolicy',
            name='template',
            field=models.JSONField(blank=True, help_text='Dictionary-based template object.', null=True, validators=[django_slack_bot.utils.validators.dict_template_validator], verbose_name='Message template object'),
        ),
    ]
