# Generated by Django 3.2.23 on 2023-12-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0004_slackmessagingpolicy_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmessagerecipient',
            name='alias',
            field=models.CharField(default='123', help_text='Alias for this recipient.', max_length=256, unique=True, verbose_name='Alias'),
            preserve_default=False,
        ),
    ]
