# Generated by Django 4.2.9 on 2024-01-05 15:27

from django.db import migrations, models

import django_slack_bot.utils.slack


class Migration(migrations.Migration):
    dependencies = [
        ("django_slack_bot", "0004_alter_slackmessagerecipient_mentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackmessage",
            name="header",
            field=models.JSONField(
                default=dict,
                help_text="Slack control arguments. Allowed fields are `mrkdwn`, `parse`, `reply_broadcast`, `thread_ts`, `unfurl_links`, `unfurl_media`.",  # noqa: E501
                validators=[django_slack_bot.utils.slack.header_validator],
                verbose_name="Header",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="slackmessage",
            name="body",
            field=models.JSONField(
                help_text="Message body. Allowed fields are `attachments`, `body`, `text`, `icon_emoji`, `icon_url`, `metadata`, `username`.",  # noqa: E501
                validators=[django_slack_bot.utils.slack.body_validator],
                verbose_name="Body",
            ),
        ),
    ]
