# Generated by Django 3.2.23 on 2023-12-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0005_slackmessagerecipient_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackmessage',
            name='channel',
            field=models.CharField(default='', help_text='Channel name this message sent to.', max_length=128, verbose_name='Channel'),
            preserve_default=False,
        ),
    ]
