# Generated by Django 3.2.23 on 2023-12-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0005_slackmessagerecipient_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackmessage',
            name='parent_ts',
        ),
    ]
