# Generated by Django 4.2.9 on 2024-01-06 07:35

from django.db import migrations, models

import django_slack_bot.utils.slack


class Migration(migrations.Migration):
    dependencies = [
        ("django_slack_bot", "0005_slackmessage_header_alter_slackmessage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackmessagingpolicy",
            name="header_defaults",
            field=models.JSONField(
                default=dict,
                help_text="Default header values applied to messages on creation.",
                validators=[django_slack_bot.utils.slack.header_validator],
                verbose_name="Default header",
            ),
        ),
        migrations.AlterField(
            model_name="slackmessage",
            name="channel",
            field=models.CharField(
                help_text="ID of channel this message sent to.",
                max_length=128,
                verbose_name="Channel",
            ),
        ),
    ]
