# Generated by Django 4.2.9 on 2024-01-07 08:23

from django.db import migrations, models

import django_slack_bot.utils.slack.django


class Migration(migrations.Migration):
    dependencies = [
        ("django_slack_bot", "0006_slackmessagingpolicy_header_defaults_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackmessage",
            name="permalink",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Permanent link for this message.",
                max_length=256,
                verbose_name="Permalink",
            ),
        ),
        migrations.AlterField(
            model_name="slackmessagingpolicy",
            name="header_defaults",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default header values applied to messages on creation.",
                validators=[django_slack_bot.utils.slack.django.header_validator],
                verbose_name="Default header",
            ),
        ),
    ]
