# Generated by Django 3.2.23 on 2023-12-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_slack_bot', '0006_slackmessage_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackmessagerecipient',
            name='channel',
            field=models.CharField(help_text='Slack channel where messages will be sent.', max_length=128, verbose_name='Channel'),
        ),
    ]
