# Generated by Django 4.2.9 on 2024-01-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_slack_bot", "0007_slackmessage_permalink_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slackmention",
            old_name="mention",
            new_name="mention_id",
        ),
        migrations.AlterField(
            model_name="slackmention",
            name="mention_id",
            field=models.CharField(
                default="",
                help_text="User or group ID, or raw mention itself.",
                max_length=32,
                verbose_name="Mention ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="slackmessagerecipient",
            name="channel_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name of channel.",
                max_length=256,
                verbose_name="Channel name",
            ),
        ),
    ]
