# Generated by Django 4.2.18 on 2025-02-10 13:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack_messages", "0006_alter_slackmessage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackmessage",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
