# Generated by Django 4.2.20 on 2025-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack_messages", "0006_alter_slackmessage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackmessagingpolicy",
            name="template",
            field=models.JSONField(
                blank=True,
                help_text="Django template name, inline content, JSON object, whatever the template type wants.",
                null=True,
                verbose_name="Message template object",
            ),
        ),
    ]
