# Generated by Django 4.2.9 on 2024-01-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackmessage",
            name="exception",
            field=models.TextField(blank=True, help_text="Exception message if any.", verbose_name="Exception"),
        ),
    ]
